include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.config.dart"
    - "**/*.g.dart"
    - "**/*.module.dart"
linter:
  rules:
    - avoid_redundant_argument_values
    - always_declare_return_types
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_relative_imports
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - use_super_parameters
